// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hellogrpc.proto

package com.stackmachine.hellogrpc;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hellogrpc.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
